spring:
  application:
    name: ries-requisitions-service
server:
  port: 9089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    lease: 5
    healthcheck:
      enabled: false
  instance:
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 60