spring:
  application:
    name: ries-requisitions-service
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://ec2-13-58-151-115.us-east-2.compute.amazonaws.com:8761/eureka
    lease: 5
    healthcheck:
      enabled: false
  instance:
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 60