spring:
  application:
    name: ries-edge-server

zuul:
  prefix: /ries
  routes:
    users:
      path: /user/**
      serviceId: ries-user-service
    requisitions:
      path: /requisition/**
      serviceId: ries-requisition-service
    signaling:
      path: /signaling/**
      serviceId: ries-signaling-service
  ignored-services: "*"

server:
  port: 9000
management:
  security:
    enabled: false

eureka:
  client:
    healthCheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseExpirationDurationInSeconds: 2
    leaseRenewalIntervalInSeconds: 1