spring:
  application:
    name: ries-edge-server


zuul:
  prefix: /ries
  routes:
    users:
      path: /user/**
      serviceId: ries-user-service
    requisitions:
      path: /requisition/**
      serviceId: ries-requisition-service
    signaling:
      path: /signaling/**
      serviceId: ries-signaling-service
  ignored-services: "*"


#server:
#  port: 9000
management:
  security:
    enabled: false

eureka:
  client:
    healthCheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseExpirationDurationInSeconds: 2
    leaseRenewalIntervalInSeconds: 1

security:
  oauth2:
    client:
      client-id: 3MVG9ahGHqp.k2_wb8eUMtoR38_WbYxUPAgheLOPEgoU4jCdw5EKilrUbtX4cxh0X0Kk2GEexJCqbOsMsD0Sm
      client-secret: 9101950503076607108
      access-token-uri: https://test.salesforce.com/services/oauth2/token
      user-authorization-uri: https://test.salesforce.com/services/oauth2/authorize
      client-authentication-scheme: form
      authentication-scheme: header
      grant-type: authentication-code
    resource:
      user-info-uri: https://revature--int1.cs17.my.salesforce.com/services/oauth2/userinfo