spring:
  application:
    name: ries-auth-service

  datasource:
    url: jdbc:oracle:thin:@ries-data.chueiwozbnfz.us-east-1.rds.amazonaws.com:1521:ORCL
    username: ries_master
    password: ries-master-password

  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Oracle10gDialect
          hbm2ddl:
            auto: update

server:
  port: 8081
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: password
#    keyStoreType: PKCS12
#    keyAlias: tomcat

eureka:
  client:
    healthCheck:
      enabled: true
    serviceUrl:
      defaultZone: http://ec2-13-58-151-115.us-east-2.compute.amazonaws.com:8761/eureka
      #defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 30
    lease-expiration-duration-in-seconds: 90

salesforce:
  oath2-url: https://test.salesforce.com/services/oauth2
  revoke: ${salesforce.oath2-url}/revoke

security:
  oauth2:
    client:
      client-id: 3MVG9ahGHqp.k2_wb8eUMtoR38_WbYxUPAgheLOPEgoU4jCdw5EKilrUbtX4cxh0X0Kk2GEexJCqbOsMsD0Sm
      client-secret: 9101950503076607108
      access-token-uri: ${salesforce.oath2-url}/token
      user-authorization-uri: ${salesforce.oath2-url}/authorize
      client-authentication-scheme: form
      authentication-scheme: header
      grant-type: authentication-code
    resource:
      user-info-uri: ${salesforce.oath2-url}/userinfo
  basic:
    enabled: false