security:
  oauth2:
    client:
      token-name:
      client-id: 3MVG9zlTNB8o8BA23PJ1557KE_0ULmPd2JgLpyeHWHyegO7Z4Hh.QeqGhOEZjZ8xeqJKuaGFWE554NDuXwVoP
      client-secret: 5464748171211685513
      access-token-uri: https://login.salesforce.com/services/oauth2/token
      user-authorization-uri: https://login.salesforce.com/services/oauth2/authorize
      client-authentication-scheme: form
      authentication-scheme: header
      grant-type: authentication-code
    resource:
      user-info-uri: https://login.salesforce.com/services/oauth2/userinfo
