spring:
  application:
    name: ries-auth-service

  datasource:
    url: jdbc:oracle:thin:@ries-data.chueiwozbnfz.us-east-1.rds.amazonaws.com:1521:ORCL
    username: ries_master
    password: ries-master-password

  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Oracle10gDialect
          hbm2ddl:
            auto: update

server:
  port: 8081
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: password
#    keyStoreType: PKCS12
#    keyAlias: tomcat

eureka:
  client:
    healthCheck:
      enabled: true
    serviceUrl:
      defaultZone: http://ec2-13-58-151-115.us-east-2.compute.amazonaws.com:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 30
    lease-expiration-duration-in-seconds: 90