spring:
  application:
    name: ries-signaling-service
server:
  port: 9092
eureka:
  client:
    service-url:
      defaultZone: http://ec2-13-59-237-239.us-east-2.compute.amazonaws.com:8761/eureka
    lease: 5
    healthcheck:
      enabled: false
